name: Inspect Contexts
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - name: Inspect contexts
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
      - name: Get Label
        run: echo ${{ github.event.pull_request.labels }}