name: Inspect Contexts
on: [push, pull_request]
jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - name: Inspect contexts
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"
      - name: Success Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Test 👌'
          SLACK_ICON: https://cdn.iconscout.com/icon/free/png-64/typescript-1-1175078.png
          SLACK_WEBHOOK: ${{ secrets.ALEX_PLANABLE_SLACK_DM_WEBHOOK }}
          SLACK_USERNAME: TestBot
          MSG_MINIMAL: actions url
          SLACK_MESSAGE: ${{ github.event.pull_request.title }}
          SLACK_FOOTER: '' 
