name: Inspect Contexts
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - name: show context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get Label
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: echo "$LABELS"
      - name: Get Value
        env:
          VALUE: ${{ contains(github.event.pull_request.labels,'Used to run all E2E tests') }}
        run: echo "$VALUE"