name: Dynamic Matrix  

on:
  push:
    branches:
      - master

jobs:
  getArray:
    runs-on: ubuntu-latest
    outputs:
      outputArr: ${{ steps.set-matrix.outputs.outputArr }}
    steps:
      - name: set-matrix
        id: set-matrix
        uses: tommy-anderson/Output-array-action@v1.5

  calculate-matrix:
    runs-on: ubuntu-latest
    needs: getArray
    strategy:
      matrix: 
        element: ${{ fromJson(needs.getArray.outputs.outputArr) }}
    steps:
      - name: Print ${{ matrix.element }}
        run: echo ${{ matrix.element }}
